name: test
on:
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.2', 'latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ['3.2', '3.4', '3.6', 'latest']
    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - name: Cache .cabal
        uses: actions/cache@preview
        with:
          path: ~/.cabal/store
          key: ${{ matrix.ghc }}-cabal-${{ hashFiles('**/fallible.cabal') }}
          restore-keys: |
            ${{ matrix.ghc }}-cabal-
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build & test
        run: |
          cabal v2-build
          cabal v2-test
